#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path:     /test
    controller: App\Controller\Test::list
    
lista:
  path: /list/{id}
  controller: App\Controller\ListaController::list
  
create:
  path: /create
  controller: App\Controller\ListaController::create
  
add_product:
  path: /add/{id}/{produto}
  controller: App\Controller\ListaController::add
  
productos:
  path: /produtos
  controller: App\Controller\ProductController::produtos