#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path:     /test
    controller: App\Controller\Test::list
    
lista:
  path: /list/{id}
  controller: App\Controller\ListaController::list
  
cenas:
  path: /cenas
  controller: App\Controller\ListaController::index